#!/bin/bash

. subs.sh

while getopts g: foo ; do
    if [ "$foo" = 'g' ]; then
        opts="-g $OPTARG"
    fi
done
shift $((OPTIND-1))

if [ $# -lt 2 ]; then
    echo -e "\nUsage: $0 [options] db.fa input.fa [blat options] > out.delta

    Options:
        -g gap          maximum gap allowed (default 5)
"
    exit 1
fi

db="$1" ; shift
input="$1"  ; shift

run "blat '$db' '$input' stdout $* -out=pslx | psl2delta $opts - '$db' '$input'"
