#!/bin/bash

if [ $# -ne 3 ]; then
    echo -e "\nUsage: $0 input.fa MLST_sequences.fa strains.txt > outfile.txt\n"
    exit 1
fi
nucmer.get_best_hits $1 $2
delta.list out.delta.q | get_best_hit qname score | ncols qname score > my_best.txt
get_best_mlst_match my_best.txt $3 | sort_file avg_score/nr
