#!/bin/bash

if [ $# -lt 2 ]; then
	echo -e "\nUsage: $0 file.fa new-file.fa\n"
	exit 1
fi

tmpdir=/usr/local/tmp/tmpred.$$
mkdir $tmpdir
splitfasta -p 200 $tmpdir "$1"

for i in $tmpdir/*.fa
do
	job.add2 "tmpred_fasta $i $i.new 2> $i.err"
done
job.wait tmpred
cat $tmpdir/*.new > "$2"
echo rm -rf $tmpdir
